# Generated by Django 4.1.5 on 2023-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_clubmember_usernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='balance',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
