# Generated by Django 4.1.5 on 2023-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_clubmember_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='clubname',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
