# Generated by Django 4.1.5 on 2023-01-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_clubmember_clubname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='usernum',
            new_name='username',
        ),
    ]
