# Generated by Django 4.1.5 on 2023-01-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=3)),
                ('dateShowing', models.DateTimeField()),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
